### ISSUE TITLE
Unknown arguments: extend-drupal8, namespace

### ISSUE THREAD

**Issue by themarkappleby** [kalamuna/kalastatic#526]
After following the getting started steps in the readme and running `kalastatic start` I am getting the following error: `Unknown arguments: extend-drupal8, namespace` (and my start/build fails). I did not attempt to set this up within a Drupal project, is this a requirement?

**Comment by RobLoach** [comment]
PR up over at https://github.com/kalamuna/kalastatic/pull/525 to allow disabling the Twig extensions.

I updated the docs a bit to accommodate. kstat-kss-builder is rooted as part of KSTAT now, so we don't need it. I'll tweak the Getting Started docs a bit futher.

**Comment by RobLoach** [comment]
@themarkappleby We've released a new alpha of Kalastatic. Feel free to try out targetting alpha1 and see if this fixes your issue. Thanks!

**Comment by themarkappleby** [comment]
Hmm, I just tried it out with 4.0.0-alpha1 and I am still getting the same error (`Unknown arguments: extend-drupal8, namespace`). I copy and pasted the `index.html.pug` and `kalastatic.yaml` contents from the readme. My directory structure looks like this:
```
project/
  - build/
  - kalastatic.yaml
  - node_modules/
    - ...
  - package.json
  - src/
    - index.html.pug
```

**Comment by thiagodemellobueno** [comment]
@RobLoach bump!
